services:
  - type: web
    name: zap-backend
    env: node
    region: singapore
    buildCommand: npm run build
    startCommand: npm start
    rootDir: packages/backend
    envVars:
      - key: HOST
        fromService:
          name: zap-backend
          type: web
          envVarKey: RENDER_EXTERNAL_HOSTNAME
      - key: POSTGRES_HOST
        fromDatabase:
          name: zap-database
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: zap-database
          property: port
      - key: POSTGRES_DATABASE
        fromDatabase:
          name: zap-database
          property: database
      - key: POSTGRES_USERNAME
        fromDatabase:
          name: zap-database
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: zap-database
          property: password
      - key: REDIS_HOST
        fromService:
          type: redis
          name: zap-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: zap-redis
          property: port
      - fromGroup: common-env-vars
  - type: worker
    name: zap-worker
    env: node
    region: singapore
    buildCommand: npm run build
    startCommand: npm run start:worker
    rootDir: packages/backend
    envVars:
      - key: HOST
        fromService:
          name: zap-main
          type: web
          envVarKey: RENDER_EXTERNAL_HOSTNAME
      - key: POSTGRES_HOST
        fromDatabase:
          name: zap-database
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: zap-database
          property: port
      - key: POSTGRES_DATABASE
        fromDatabase:
          name: zap-database
          property: database
      - key: POSTGRES_USERNAME
        fromDatabase:
          name: zap-database
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: zap-database
          property: password
      - key: REDIS_HOST
        fromService:
          type: redis
          name: zap-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: zap-redis
          property: port
      - fromGroup: common-env-vars
  - type: redis
    name: zap-redis
    ipAllowList: [] # allow only internal connections
    maxmemoryPolicy: noeviction
databases:
  - name: zap-database
    databaseName: zap
    postgresMajorVersion: 15

envVarGroups:
  - name: common-env-vars
    envVars:
      - key: APP_ENV
        value: production
      - key: PROTOCOL
        value: https
      - key: PORT
        value: 443
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: WEBHOOK_SECRET_KEY
        generateValue: true
      - key: APP_SECRET_KEY
        generateValue: true
      - key: NODE_VERSION
        value: 18.13.0
